# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2a82f185-3a08-4dc4-9938-35a6ff8b5f34";
      fsType = "ext4";
    };

  fileSystems."/mnt/ssd" =
    { device = "/dev/disk/by-uuid/dd899653-95d8-4e2b-9539-e1cea5d05bc7";
      fsType = "btrfs";
      options = [
        "acl"
        "defaults"
        "nofail"
        "compress=zstd:3"
        "noatime"
      ];
    };



  boot.initrd.luks.devices."luks-f8874a5f-5715-4816-9001-fe20e55a1148".device = "/dev/disk/by-uuid/f8874a5f-5715-4816-9001-fe20e55a1148";
  boot.initrd.luks.devices."luks-f6deb340-f2f5-4142-97e8-10c326606094".device = "/dev/disk/by-uuid/f6deb340-f2f5-4142-97e8-10c326606094";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/E178-10C0";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/745b14bc-6d87-45d3-8dd6-d2721481ad16"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
